// Chat or messages
exports.NO_MESSAGE_PROVIDED = 300;
exports.MESSAGE_NOT_CREATED = 301;
exports.CHAT_NOT_CREATED = 302;
exports.ERROR_INIT_CHAT = 303;
exports.CHAT_NOT_FOUND = 304;
exports.CHAT_ID_REQUIRED = 305;
exports.MESSAGE_ID_REQUIRED = 306;
exports.ERROR_REMOVING_USER = 307;
exports.CHAT_EXPIRED = 304;



// User errors
exports.USERNAME_ALREADY_TAKEN = 200;
exports.USERNAME_NOT_FOUND = 201;
exports.USERNAME_IS_REQUIRED = 203;
exports.USER_ID_REQUIRED = 204;

// Cloudinary
exports.UPLOAD_STREAM_ERROR = 100;
exports.NO_IMAGES = 101;
exports.ERROR_REMOVING = 102;


// Others
exports.HASHING_ERROR = 405;
exports.INCORRECT_PASSWORD = 406;
exports.REQ_BODY_REQUIRED = 407;
